#!/bin/zsh

q=`cat ~/Documents/.calc_history.txt | rofi -dmenu -i -p "CALC" -theme "~/.config/rofi/config.rasi" -font "Hack 18"`
if [ "$q" != "" ]
then
	ans="$(python ~/bin/calc.py $q)"
	notify-send "$q = $ans"
	echo "$q" >> ~/Documents/.calc_history.txt
	echo "= $ans" >> ~/Documents/.calc_history.txt
fi
