#!/bin/zsh

cd ~/Documents/UNC/Spring\ 2020/
class=`ls -d */ | sed 's#/##'| rofi -dmenu -theme "~/.config/rofi/config.rasi" -i -p "CLASS" -font "Hack 18"`
if [ "$class" != "" ]
then
	cd $class
	note=`ls | sort | rofi -dmenu -theme "~/.config/rofi/config.rasi" -i -p "NOTE" -font "Hack 18"`
	if [ "$note" != "" ]
	then
		if [ "$note" = "NEW" ]
		then
			date="$(date +'%m-%d-%Y')"
			note="$date.odt"
			if [ -f "$note" ]
			then
				soffice "$note"
			else
				touch "$note"
				className="${PWD##*/}"
				title="$className\n$date\n"
				echo "$title" > $note
				soffice "$note"
			fi
		else
			soffice "$note"
		fi
	fi
fi

