#!/bin/zsh

class=`ls -d ~/Documents/UNC/Spring\ 2020/*/ | rofi -dmenu -theme "~/.config/rofi/config.rasi" -i -p "TODO" -font "Hack 18"`
if [ "$class" != "" ]
then
	cd $class
	date="$(date +'%m-%d-%Y')"
	note="$date.odt"
	touch "$note"
	className="${PWD##*/}"
	title="$className\n$date\n"
	echo "$title" > $note
	soffice "$note"
fi

