#!/bin/zsh

option=`sort -k 1 ~/Documents/.todo.txt | rofi -dmenu -theme "~/.config/rofi/config.rasi" -i -p "TODO" -font "Hack 18"`
if [ "$option" != "" ]
then
	selection=`cat ~/Documents/.todo.txt | grep "$option"`
	if [ "$selection" !=  "" ]
	then
		sed -i /"$selection"/d ~/Documents/.todo.txt
        ./bin/todo
	elif [ "$option" = "EDIT" ]
	then
		xdg-open ~/Documents/.todo.txt
	else
		echo "$option" >> ~/Documents/.todo.txt
		date_string=$(echo $option | head -n1 | awk '{print $1;}')
		date=$(echo $date_string | sed "s/-/\//g" | sed "s/*//g")
		remind_date=$(date -d "$date-1 day" "+%m/%d"/%Y)
		echo "notify-send 'TODO' '$option'" | at 9:00AM "$remind_date"
    ./bin/todo
	fi
fi
