#!/bin/zsh

BAND=`ls ~/Music/ | rofi -rofi -dmenu -theme "~/.config/rofi/config.rasi" -i -p "BAND" -font "Hack 18"`

if [ "$BAND" != "" ]
then
	if [ -d ~/Music/$BAND ]
	then
		cd ~/Music/$BAND
		while [ 1 ]
		do
			ALBUM=`ls ~/Music/$BAND/ | rofi -rofi -dmenu -theme "~/.config/rofi/config.rasi" -i -p "ALBUM" -font "Hack 18"`
			if [ "$ALBUM" != "" ]
			then
				if [ -d ./$ALBUM ]
				then
					continue
				else
					mkdir $ALBUM
					cd $ALBUM
					URL=`rofi -rofi -dmenu -theme "~/.config/rofi/config.rasi" -i -p "URL" -font "Hack 18"`
					if [ "$URL" != "" ]
					then
						youtube-dl -x --embed-thumbnail --audio-format mp3 -o "%(playlist_index)s-%(title)s.%(ext)s" $URL
						id3v2 * -a $BAND -A $ALBUM
						break
					else
						cd ..
						rm -R $ALBUM
						break
					fi
				fi
			else
				break
			fi
		done
	else
		mkdir ~/Music/$BAND
		cd ~/Music/$BAND
        	while [ 1 ]
                do
                  	ALBUM=`ls ~/Music/$BAND/ | rofi -rofi -dmenu -theme "~/.config/rofi/config.rasi" -i -p "ALBUM" -font "Hack 18"`
                        if [ "$ALBUM" != "" ]
                        then
                        	mkdir $ALBUM
                                cd $ALBUM
                                URL=`rofi -rofi -dmenu -theme "~/.config/rofi/config.rasi" -i -p "URL" -font "Hack 18"`
                                if [ "$URL" != "" ]
                                then
                                	youtube-dl -x --embed-thumbnail --audio-format mp3 -o "%(playlist_index)s-%(title)s.%(ext)s" $URL
                                        id3v2 * -a $BAND -A $ALBUM
                                        break
				else
                                       	cd ..
                                        rm -R $ALBUM
					cd ..
					rm -R $BAND
                                        break
                        	fi
                        else
				cd ..
				rm -R $BAND
                            	break
                        fi
                done
	fi
fi
