#!/bin/zsh

if [ -d ~/Music/$1 ]
then
	cd ~/Music/$1
	if [ -d ./$2 ]
	then
		echo "Album Already Exists"
	else
		mkdir $2
		cd $2
		youtube-dl -x --embed-thumbnail --audio-format mp3 $3
		id3v2 * -a $1 -A $2
	fi
else
	mkdir ~/Music/$1
	cd ~/Music/$1
	mkdir $2
	cd $2
	youtube-dl -x --embed-thumbnail --audio-format mp3 $3
	id3v2 * -a $1 -A $2
fi
